### ISSUE TITLE
REGR: UserDefined classifier returns ValueError("Minimum and maximum of input data are equal, cannot create bins.")

### ISSUE THREAD

**Issue by martinfleis** [pysal/mapclassify#100]
We have a regression in 2.4.0. This commit https://github.com/pysal/mapclassify/commit/7aad6fca0521cc29c64d43a1618dabd16a1ea965 introduced the following check:

https://github.com/pysal/mapclassify/blob/b92a7e3951c2adb4d25872704a096c20c8d78e44/mapclassify/classifiers.py#L632-L633

However, that is irrelevant if you use `UserDefined` classifier. momepy's [CI](https://github.com/martinfleis/momepy/runs/1567354940?check_suite_focus=true#step:6:109) got red with 2.4.0. I define bins using the whole array and then using the same in subsets of data to get counts per bin, therefore it is perfectly fine that `min == max`.

Would not be better to fall back to `k=1` and raise a warning instead of an error in general? You may have discussed that before though... (cc @jeffcsauer)

We should ideally fix this and do 2.4.1 bugfix release before we'll do meta release.

**Comment by jeffcsauer** [comment]
@martinfleis ah gotcha, your use case makes sense and I can understand why this solution wouldn't hold! Commit 7aad6fc was meant to directly fix [this error](https://github.com/pysal/mapclassify/issues/88) during the sprint. I used ValueError as the user had mentioned it in the post, but I agree with you, warning would be better. 

So perhaps something like: 

```
if min(self.y) == max(self.y): 
     k=1
     warnings.warn("Minimum and maximum of input data are equal, please ensure that bins are appropriate.")
```

Not sure what the best message would say. 

Feel free to overwrite/reverse my commit, otherwise I'm happy to make another.
