### ISSUE TITLE
mapclassify.Natural_Break() does not return the specified k classes

### ISSUE THREAD

**Issue by mingchau** [pysal/mapclassify#16]
Hi,

I use mapclassfiy.Natural_Break() to produce bins for my MapBox heatmap.

My code like this:
`df = pd.read_table('./files_output/customer_qty.txt',sep=',',header=None).iloc[:,1] `
`mapclassify.Natural_Breaks(df.iloc[:,1], k=5)`

In my thought it should return 5 classes, but it only returned 3 classes

.
The output is:

>  Natural_Breaks               
>  
>  Lower            Upper                 Count
 =============================================
>           x[i] <=   1.000               54428
>   1.000 < x[i] <=  26.000                2475
>  26.000 < x[i] <= 212.000                  66
> 

Attachment is the `customer_qty.txt` data file.
[customer_qty.txt](https://github.com/pysal/mapclassify/files/2513751/customer_qty.txt)

**Comment by weikang9009** [comment]
Thank you for opening the issue. 

I think the problem lies in the [kmeans function from scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.vq.kmeans.html#scipy.cluster.vq.kmeans) used in mapclassify.Natural_Breaks to cluster the input data. This issue is related to issues  [1](https://stackoverflow.com/questions/47743928/scipy-kmeans-returning-less-clusters-than-the-passed-number-of-centroids-argumen) and [2](https://stackoverflow.com/questions/8720815/what-to-do-when-kmeans-returns-fewer-than-k-clusters) opened in stackoverflow. The point is that k-means can fail in the sense that clusters can disappear if no data points are assigned to a cluster center in the iterative process. Therefore, a smarter initial selection of cluster center is important and one such initial smarter selection is implemented [ in sklearn (init=’k-means++’)](http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans). I think it makes sense to switch from scipy to sklearn to make sure that the returned number of classification is identical as specified @sjsrey @ljwolf ?
