### ISSUE TITLE
Add VBA functionality

### ISSUE THREAD

**Issue by sjsrey** [pysal/mapclassify#37]
Following the suggestions raised in #36 by @slumnitz.

**Comment by darribas** [comment]
How would this work exactly? Just opening the discussion.

My main concern is in making intuitive the classification of the `vba` variable given the classification of the main variable is obvious since this will be a method of a given classifier. For example given a continuous variable `y`:

```python
classi = Quantiles (y)
classi.plot(geoms)
```

This would be a standard choropleth. Now, if I have another variable (e.g. `confidence`) that I want to use to modulate alpha values. How should this be passed in? More importantly, how should we allow the user to determine the classiffication scheme for that? A couple of ideas (totally brainstorming so might not make sense):

1. We use the style of `choropleth_vba` and allow the user to pass any classifier. This is consistent but a bit awkward in a way since they would pick the classifier for `y` in one way and for `confidence` in another)
2. We don't allow the user to pass classifiers for `vba` and use the same classifier and same parameters for `confidence` as used for `y`. This is consistent within the method and simpler to set up but arguably a bit too restrictive.
3. Something in the middle?

**Comment by sjsrey** [comment]
Another possibility:
```
class_a = Quantiles(a)
class_b = Quantiles(b)
vba.plot(class_a, class_b)
```

where `vba` is an instance of a new class.

I think loading up the plot method in the univariate classifiers is going to complicated things.

**Comment by darribas** [comment]
I really like that approach. I'd maybe call it `choropleth` instead of `vba`?

**Comment by slumnitz** [comment]
`splot.vba_chorpleth` actually does exactly this under the hood. For maintaining purposes we might want to consider to leverage functionality for both and just store it at one place.

**Comment by martinfleis** [comment]
Can this be closed since the plotting is in splot?

**Comment by jGaboardi** [comment]
I think so. We can reopen if needed.
